const x = 10


// tentar mudar o valor de uma const - isso da um erro 

try {
    x = 2

} catch (err) {
    console.log(`Erro: ${err}`)
}

console.log('continuandoo c√≥digo...')


